# Generated by Django 5.0.1 on 2024-02-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitescrapper_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='stringname',
            new_name='string_name',
        ),
    ]
